---
title: "Grad School Advice"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
<style>
body {
text-align: justify}
</style>
<br  />

#### Some general advice for graduate students


**Update July 9, 2019**: I get a lot of emails about this page, with many common questions. I am thinking of writing a follow-up article to this one - if you have ideas, questions that this article, or the linked ones, don't answer, or you want to co-write a follow-up with me, [email me](mailto:anusha.shankar@cornell.edu)!

### Helpful Links
A quick google search will lead you to many links on how to get the most of your grad student experience. For example: <br>
An article by a current Cornell graduate student (Janani Hariharan) on "[the hidden curriculum]()" for international students - some things that people don't tell you about the culture of academia in the US that are helpful to know when you start your program! She also has a [guide document]() for international students looking to join a graduate program!
For Indian students aspiring to do ecology, take a look below and at [Sahila Kudalkar's post].
<!-- Links to many useful guides are listed on [Jennie Miller's page](). -->
Science has a series of [useful articles]() on selecting a graduate school and adviser, as well as on publishing scientific papers.
When talking with potential advisers or others in the department you are interviewing with, here's a [great thread]() with ideas for questions you can ask them. Remember that you are evaluating them as much as they are evaluating you!

### Listservs that advertise jobs
You can find advertised positions at various career levels (from field-tech to Master's, PhD, postdoc, government jobs, faculty positions) at these listservs: [Ecolog-L]() (ecology-related), [EvolDir]() (evolutionary biology related), [Texas A&M](), and many other society-specific listservs depending on your field (e.g. [Animal Behavior Society]()) or taxon ([Ornithology Exchange](), birds) of interest. Many jobs are advertised on Twitter- so it might be useful to create a science Twitter account for yourself.
<br  />


### On Applying for graduate programs
(Sept 2013, with small edits Feb 2015, Dec 2016)<br>
Below is a document I wrote as a guide targeted at foreign students applying for PhD programs, primarily in the US (Here it is as a [PDF](https://anushashankar.weebly.com/uploads/1/3/9/6/13968642/on_applying_abroad.pdf)).<br>
If you want access to an Excel spreadsheet that I made to help me plan out my grad school applications (because it gets pretty unmanageable quite quickly if you do it right), then [email me](mailto:anusha.shankar@cornell.edu)!<br>
Everything I have written here comes from my own experience, and from reading lots and lots of websites. Written initially for my juniors at the Ecology department in Pondicherry, India. Sahila Kudalkar has also provided valuable improvements and comments.


**Application Deadlines**: <br>    
I start with this because these are what will help you plan your application process. Applying for a PhD abroad takes time. Be prepared to invest a lot of effort and time in applying. If you want to study abroad, you will have to work for it. Most deadlines for M.Sc. and PhD programmes start on December 1st of the previous academic year. This means all your application materials need to be submitted by this date, say Dec 1st 2013 of you want to join in August 2014. Some universities have January deadlines, and some have March. But, for most, if you want a fellowship or any kind of funding, the earlier you apply, the better. Remember that the things that take the most time are Transcripts and recommendations- you need to start these especially early. Most application processes are largely online nowadays.
<br  />

**Funding**: <br>
Funding is not very good right now, for many programmes, because of the current economic situation all over the world. However, you can find fellowships, scholarships, or assistantships, to fund your study. An assistantship is usually either a TA (teaching assistantship), or an RA (research assistantship), where you teach UG students, or get paid to do research respectively. Many universities offer one of these to all admitted PhD students. Additionally, do check out the JN Tata Endowment Loan [Scholarships](http://bit.ly/1j0qZ7x) for the Higher Education of Indians- they provide travel grants as well. If you have previous work experience, it would also be useful to check out Fulbright scholarships during the application process. The Ravi Sankaran Foundation is another organization that supports higher education of students studying environmental sciences.
<br  />

**How many universities/schools should I apply to?**
This could vary depending on your level of experience and qualifications, but if you are at a loss for how many applications to send in, the general guideline is 8-10 programs. I've heard many people suggest that you apply to:
1)  2-4 schools that you would really love to go to- that may have low admission rates but that you would regret if you didn't apply to. These might have world-renowned programs in your field.
2)  3-4 schools that you are pretty sure you will get into, that are good schools that people have heard of, ones that you come across many papers in your field from, perhaps.
3)  2-3 schools that are 'backup schools' that you think you would be very well qualified for, and should get admission to given your qualifications.
<br  />

**How do I find universities to apply to?**
The easiest way is to find people you know who study in your field in the country/countries you'd like to study in, and ask them for advice. But if you're reading this there is a chance you might not know that many such people. The next way, which might be the best way, is to read journal articles in your field(s) of interest, and select some of your favorite articles. Who authored those articles? Go to their websites- do they currently do work you are interested in? Are they looking for students? Then, look at articles that have cited the articles you like, and look at their authors and go through the same process. Make sure to keep track of your findings, at least the ones that look promising, in a Word document or an Excel file, because you can quickly lose track of your searches. Paste links to their websites, save their email addresses, and any other notes to your future self, all into that document/spreadsheet, to make your life easier. On the same document, you can later start keeping track of who you've written to, who's responded, the status of your application, and so on. Feel free to email me for a sample spreadsheet.
<br  />

### What they ask for
*Application Form*- Usually made up of a series of online forms, where you fill in your personal details, what course you are applying to, GPA, GRE and TOEFL scores, SOP, referee names, and so on [see below]. 
GRE ([Graduate Record Examination](www.ets.org/gre)) General exam Scores - essentially a test of English and basic mathematics. The GRE is required for most post-graduate studies in the US, usually not required for the UK/Europe/Australia. Ideally should be taken between June and late September- early October. NOT later. When I wrote it in 2009, this exam cost Rs. 8000. Check the cost before applying, and be sure that you want to apply to the US (Not very useful otherwise). Scores take 2 weeks to be reported after your test date, and you should leave a month for them to reach the university you are applying to (Same for TOEFL).
<br  />

*TOEFL* ([Test of English as a Foreign Language](http://www.ets.org/toefl)). An english exam (much simpler than GRE english), required mainly to prove that you know enough to speak/read/write English when you’re going to European/Australian/American universities. It is largely for the visa requirement that they ask for this exam. This exam cost Rs. 6000 when I wrote it in 2010. IELTS (International English Language Testing System) is another accepted English exam. Which test you should take depends on the country you are applying to. TOEFL is more for the US, and IELTS more for the UK. But both are accepted in most places.
<br  />

*CV- Curriculum Vitae*- sometimes called a Resumé, but they're quite different from each other. You do not have to include your address and a line saying “Objective”. Most people write “To get a PhD in your university.” This is too obvious an objective, and does not help you at all. I would suggest leaving it out. To look at [my CV](AnushaShankar_Mar2021_CV.pdf) for some ideas on formatting, you can look at. There are many many resources on the internet for CV formats- don’t just base yours on one, but instead look at multiple ones.
<br  />

*Statement of Purpose*- This is a description what you want to do. This has to be very well written, so make sure you ask someone who knows a little bit about writing to help you, or edit once you are done. Your SOP has to include why you want to pursue M.Sc./PhD/…, why in that particular university, how will this course help you, why you would fit well with their programme (spelt program in the US), your short-term and longer-term professional goals, and a brief description of how your past experiences will help you achieve this. SOPs are usually 1-2 pages long. However, some universities have word limits in the application which you will have to stick to. It is always a good idea to prepare a draft, and carefully modify it each time you are uploading it to an application, to be specific to the university. Working on your SOP carefully, and revising it as many times as it takes, is a good idea- plan that it might take you one month. Ask your friends and/or seniors for their SOP formats, and ask them to look at yours.
<br  />

*Recommendations*- This is a very important part of your application. Most universities ask for 2-4 people who can give you recommendation. It is usually the practice, when you’re applying for PhD, that at least 2 of these people have taught you or guided you on a research project. The other can be more of a character reference, or can be a teacher as well. It helps if 1-2 of these people are well known in the field.
<br  />

*Transcripts*- These are official attested copies of any one of, or a combination of, the following: semester mark sheets, consolidated marksheet, provisional degree certificate, degree certificate. You will need to get the same from both your UG and PG colleges, in sealed stamped envelopes. Each university has its own requirements for what you should send and when you should send it- some don’t need it during application, but only if you are admitted. Others need transcripts along with the application.
<br  />

### What they don’t always ask for, which you should do

**Write to profs!!** <br>
Around August-September, you should start searching for universities and professors whom you would like to work with. Once you find them, write to them saying you are interested in their work on XXX, your past experience is with YXY, and whatever else might be relevant. Your email should ideally be 2-4 paragraphs long- enough to catch their attention but not too long and boring. It is normal to attach your CV (Curriculum Vitae) or resume to this email, so they can choose to see a detailed description of your previous experience/academics. If they do not reply, you can safely resend the email after about 3 weeks, asking if they had the time to see your email. This writing to profs is very necessary for doing a higher degree abroad, as in many places they will accept you only if a professor has agreed to take you as their student. Additionally, it helps to look at the prof's list of publications, and perhaps read a couple of papers that interest you. Try to draw parallels between his past research and your proposed research path if possible. Also, while writing to the professor, it is suggested that you be professional and *avoid flowery writing*. Finally, university students abroad (especially in the USA) do not use the term 'Sir' or 'Madam' so you could initially begin with a formal 'Dr. A'. 'Dear' is rarely used as well.  Please read this excellent guide on writing a good email to a professor/for an internship!
<br  />

**What advisors look for**: <br>
I’m writing this in April 2013, after having joined the PhD program in Stony Brook in August 2012. I see now that advisers vary a lot in what they want from a student. But the key thing to understand is that there is so much luck involved in the whole process. The people you want to apply to must have funding, must have space in their lab for a new student, must have the departmental support to take an international student, must be looking for someone with your skill set, and so on. This is why you must 1. Be so good (experience + publications + scientific maturity) that they will do anything to get you to their lab, or 2. Have your own funding, or 3. (and this you should do anyway) You must write to many many many professors. Because just by luck, more than half will not have an available position. You need to check their website, see if it has anything about opportunities for students (but this is not always updated, so write anyway). If you have a good peer-reviewed publication or two, and are applying to the US for a PhD, your chances of getting in are good given all the luck aspects I just mentioned. You need research experience for sure, decent to good GRE scores and grades (because not just the prof takes you in, you are also competing with other applicants for funding from the department, and you have to measure up).
<br  />

Make sure your cover letter is attention grabbing, make sure your grammar is correct, that you have attached your (properly formatted) CV. Write again if they don’t respond in 2-3 weeks. Many professors expect you to persist, because they are sometimes too busy to reply to emails unless you really prove your interest. If you are really interested in their lab, write to their PhD students. There is a lot of interaction between advisors and other professors’ students in some departments, so it might help to get in touch with a student who might reply faster. Do not ask obsessively about funding in the first email you send to any of them, but definitely bring it up after a conversation has started. Good luck!

#### P.S. Update (added ~May 2018)
Here are some more other things I've learned in my time as a grad student.
**Take initiative and self-evaluate** - don't expect your adviser or department, however good they are, to always think about what you need. You need to think about your long-term goals for yourself, and evaluate them periodically (maybe once a month). Are you where you want to be, to achieve your 5-year goals? What else do you want to get experience in, and by what time? What are the most important elements missing on your CV, or even on your [shadow CV](? What have you not tried out, that you should try out before you graduate? A PhD is a great time to explore new fields and skills. Periodically re-evaluate! <br>
Ask for a graduate student **mentor**, or ask your program to start a graduate student mentoring program. I started such a program in mine for first year grad students and can help with tips for setting this up. Even if there is no such program, find people you respect and make them your mentors. People are good at different things- you cannot expect one person to help you with all your personal+professional needs, so make, for yourself, a network of mentors. And here's a not-so-secret secret- people generally like being mentors! It feels great to pay forward the help they got, getting where they are now! <br>
Get a **silent writing group** together, or at least a couple of writing buddies. Your success as grad student depends in large part on your writing, but many people don't treat writing time like they treat class time- as an essential part of every day (I still really struggle with this). Having a writing group helps make your writing time more regimented. And this helps a lot in the long run, especially if you like having some regular (but non-judgmental) accountability. I started a silent writing group in my department at Stony Brook, and it's been successful so far. We just sit together in a room and write quietly at certain times of the week, sometimes with some background music (search for the "Study alpha waves" playlist on Spotify).


<br />
<center>
##### Contact: Anusha Shankar  |  Twitter: [\@nushiamme](https://twitter.com/nushiamme)  |  Email: [anusha.shankar@cornell.edu](mailto:anusha.shankar@cornell.edu)
</center>

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>